-- ============================================
-- V10: Create Account Table
-- ============================================
-- This migration creates the account table for platform accounts
-- ============================================

CREATE TABLE public.account (
    id bigint NOT NULL,
    creator_id bigint NOT NULL,
    platform_user_id character varying(512) NOT NULL,
    platform_username character varying(255) NOT NULL,
    profile_link character varying(512),
    display_name character varying(255),
    is_active boolean NOT NULL DEFAULT true,
    connected_at timestamp(6) with time zone,
    disconnected_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL
);

-- Create sequence for account id
ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Primary key
ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

-- Foreign key to user (creator)
ALTER TABLE public.account
    ADD CONSTRAINT account_creator_fk
        FOREIGN KEY (creator_id)
            REFERENCES public.user(id)
            ON DELETE RESTRICT;

-- Index on creator_id for faster lookups
CREATE INDEX idx_account_creator_id
    ON public.account USING btree (creator_id);

-- Index on platform_user_id for faster lookups
CREATE INDEX idx_account_platform_user_id
    ON public.account USING btree (platform_user_id);

