-- ============================================
-- V12: Create Video Table
-- ============================================
-- This migration creates the video table for platform videos
-- ============================================

CREATE TABLE public.video (
    id bigint NOT NULL,
    contract_id bigint NOT NULL,
    account_id bigint NOT NULL,
    platform_video_id character varying(512) NOT NULL,
    platform_video_link character varying(512),
    location character varying(512),
    title character varying(512),
    description text,
    duration character varying(50),
    posted_at character varying(255),
    is_on_time character varying(50),
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone
);

-- Create sequence for video id
ALTER TABLE public.video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Primary key
ALTER TABLE ONLY public.video
    ADD CONSTRAINT video_pkey PRIMARY KEY (id);

-- Foreign key to contract
ALTER TABLE public.video
    ADD CONSTRAINT video_contract_fk
        FOREIGN KEY (contract_id)
            REFERENCES public.contract(id)
            ON DELETE RESTRICT;

-- Foreign key to account
ALTER TABLE public.video
    ADD CONSTRAINT video_account_fk
        FOREIGN KEY (account_id)
            REFERENCES public.account(id)
            ON DELETE RESTRICT;

-- Index on contract_id for faster lookups
CREATE INDEX idx_video_contract_id
    ON public.video USING btree (contract_id);

-- Index on account_id for faster lookups
CREATE INDEX idx_video_account_id
    ON public.video USING btree (account_id);

-- Index on platform_video_id for faster lookups
CREATE INDEX idx_video_platform_video_id
    ON public.video USING btree (platform_video_id);

