-- ============================================
-- V13: Create Video Analytics Table
-- ============================================
-- This migration creates the video_analytics table for historical video metrics
-- ============================================

CREATE TABLE public.video_analytics (
    id bigint NOT NULL,
    video_id bigint NOT NULL,
    views_count bigint,
    likes_count bigint,
    comments_count bigint,
    shares_count bigint,
    recorded_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone
);

-- Create sequence for video_analytics id
ALTER TABLE public.video_analytics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Primary key
ALTER TABLE ONLY public.video_analytics
    ADD CONSTRAINT video_analytics_pkey PRIMARY KEY (id);

-- Foreign key to video
ALTER TABLE public.video_analytics
    ADD CONSTRAINT video_analytics_video_fk
        FOREIGN KEY (video_id)
            REFERENCES public.video(id)
            ON DELETE RESTRICT;

-- Index on video_id for faster lookups
CREATE INDEX idx_video_analytics_video_id
    ON public.video_analytics USING btree (video_id);

-- Index on recorded_at for time-based queries
CREATE INDEX idx_video_analytics_recorded_at
    ON public.video_analytics USING btree (recorded_at);

