--
-- PostgreSQL database dump
--

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campaign; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) with time zone NOT NULL,
                                 end_at timestamp(6) with time zone,
                                 name character varying(255) NOT NULL,
                                 owner_id bigint NOT NULL,
                                 start_at timestamp(6) with time zone
);


--
-- Name: campaign_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campaign ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

--
-- Name: contract; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contract (
                                 id bigint NOT NULL,
                                 campaign_id bigint NOT NULL,
                                 completed_at timestamp(6) with time zone,
                                 created_at timestamp(6) with time zone NOT NULL,
                                 creator_id bigint NOT NULL,
                                 deadline timestamp(6) with time zone NOT NULL,
                                 expected_posts integer NOT NULL,
                                 is_complete boolean,
                                 retainer_cents bigint
);


--
-- Name: contract_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



--
-- Name: campaign campaign_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign
    ADD CONSTRAINT campaign_pkey PRIMARY KEY (id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--