--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    is_creator boolean,
    is_owner boolean,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user user_username_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_username_unique UNIQUE (username);


--
-- Name: user user_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: user user_has_role_check; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_has_role_check CHECK (is_creator = true OR is_owner = true);


-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================

-- User: Index on email for login lookups
CREATE INDEX idx_user_email
    ON public."user" USING btree (email) WHERE deleted_at IS NULL;


-- User: Index on username for login lookups
CREATE INDEX idx_user_username
    ON public."user" USING btree (username) WHERE deleted_at IS NULL;


-- User: Index on deleted_at for soft delete queries
CREATE INDEX idx_user_deleted_at
    ON public."user" USING btree (deleted_at) WHERE deleted_at IS NULL;

