spring.application.name=Vizor

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=jdbc:postgresql://localhost:5433/vizor
spring.datasource.username=dev
spring.datasource.password=vizor2025

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=your-256-bit-secret-key-change-this-in-production-minimum-32-characters
jwt.expirationMinutes=1440

